Part 3: Updating dev with designer's map branch
UNIFIED-CAPSTONE-IEMC/The-Fall pull request #72
Opened 2023-11-30 15:47 UTC by KoolieAid

# Description:
Updates the dev branch with commits from the designers
Part 3

### How it works:
TBA

## Guidelines:
- [ ] I have consulted my lead when making this request
- [X] I have followed merging practices
- [X] I have assigned the proper target branch this will merge to

### Features added:
- TBA
- None

### Features removed:
- None

### Potential Affected branches:
- dev
- None

### Potential Affected features:
- None

## Leads Only
- [ ] This merge request has been approved by all the leads in my department

2023-12-02 17:13 UTC, LauSnchzz requested changes
TO DELETE DUE TO ERRORS IN BUILDING THE GAME:
- Content\PauseMenu\BP_PlayerPauseDuplicate.uasset
- Content\InspectObject\BP_PlayerDuplicate.uasset
- Content\InspectObject\BP_PlayerControllerDuplicate.uasset

EXTRA NOTE:
Content/TheFall/Levels/UMaps/Boss_Maze.umap has malformed tag. Make sure this issue is fixed before merging back to dev.

2023-12-03 13:30 UTC, KoolieAid commented on Content/TheFall/Levels/UMaps/Boss_Maze.umap
Awaiting on @chartimbreza to provide a reference for the blob.  
There was a merge conflict was not resolved but commited

2023-12-05 07:18 UTC, KoolieAid commented
Also fixes #60, github wont permit more than 10 linked issues

2023-12-12 12:05 UTC, LauSnchzz approved these changes
ok na tapos na

2023-12-12 12:26 UTC, merged